/* eslint-disable */
// AUTO-GENERATED by scripts/media.mjs from media-src/manifest.json — DO NOT EDIT. Run `npm run media`.

export type MediaPreset = "photo" | "graphic";

export type Rung = readonly [width: number, url: string];

export type ImageEntry = {
  readonly preset: MediaPreset;
  readonly width: number;
  readonly height: number;
  readonly avif: readonly Rung[];
  readonly webp?: readonly Rung[];
  readonly fallback: string;
  readonly alt?: string;
};

export type VideoEntry = {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly poster?: string;
};

export const images = {} as const satisfies Record<string, ImageEntry>;

export type MediaId = keyof typeof images;

export const galleries = {} as const satisfies Record<string, readonly MediaId[]>;

export const videos = {
  "hero": {
    src: "/media/video/hero.mp4",
    poster: "/media/video/hero-poster.webp",
    width: 1080,
    height: 574,
  },
} as const satisfies Record<string, VideoEntry>;
