/* eslint-disable */
// AUTO-GENERATED by scripts/media.mjs from media-src/manifest.json — DO NOT EDIT. Run `npm run media`.

export type MediaPreset = "photo" | "graphic";

export type Rung = readonly [width: number, url: string];

export type ImageEntry = {
  readonly preset: MediaPreset;
  readonly width: number;
  readonly height: number;
  readonly avif: readonly Rung[];
  readonly webp?: readonly Rung[];
  readonly fallback: string;
  readonly alt?: string;
};

export type VideoEntry = {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly poster?: string;
};

export const images = {
  "business-card-mockup/designcartechocolat": {
    preset: "graphic",
    width: 2400,
    height: 743,
    avif: [
      [640, "/media/business-card-mockup/designcartechocolat-640.avif"],
      [1200, "/media/business-card-mockup/designcartechocolat-1200.avif"],
      [2400, "/media/business-card-mockup/designcartechocolat-2400.avif"],
    ],
    fallback: "/media/business-card-mockup/designcartechocolat.png",
  },
  "business-card-mockup/designcarterose": {
    preset: "graphic",
    width: 2400,
    height: 740,
    avif: [
      [640, "/media/business-card-mockup/designcarterose-640.avif"],
      [1200, "/media/business-card-mockup/designcarterose-1200.avif"],
      [2400, "/media/business-card-mockup/designcarterose-2400.avif"],
    ],
    fallback: "/media/business-card-mockup/designcarterose.png",
  },
  "business-card-mockup/logoen8variantes": {
    preset: "graphic",
    width: 2274,
    height: 1313,
    avif: [
      [640, "/media/business-card-mockup/logoen8variantes-640.avif"],
      [1200, "/media/business-card-mockup/logoen8variantes-1200.avif"],
      [2274, "/media/business-card-mockup/logoen8variantes-2274.avif"],
    ],
    fallback: "/media/business-card-mockup/logoen8variantes.png",
  },
  "business-card-mockup/mockupcartechocolat": {
    preset: "photo",
    width: 1498,
    height: 1454,
    avif: [
      [640, "/media/business-card-mockup/mockupcartechocolat-640.avif"],
      [1200, "/media/business-card-mockup/mockupcartechocolat-1200.avif"],
      [1498, "/media/business-card-mockup/mockupcartechocolat-1498.avif"],
    ],
    webp: [
      [640, "/media/business-card-mockup/mockupcartechocolat-640.webp"],
      [1200, "/media/business-card-mockup/mockupcartechocolat-1200.webp"],
      [1498, "/media/business-card-mockup/mockupcartechocolat-1498.webp"],
    ],
    fallback: "/media/business-card-mockup/mockupcartechocolat.png",
  },
  "business-card-mockup/mockupcarterose": {
    preset: "photo",
    width: 1422,
    height: 1484,
    avif: [
      [613, "/media/business-card-mockup/mockupcarterose-640.avif"],
      [1150, "/media/business-card-mockup/mockupcarterose-1200.avif"],
      [1422, "/media/business-card-mockup/mockupcarterose-1484.avif"],
    ],
    webp: [
      [613, "/media/business-card-mockup/mockupcarterose-640.webp"],
      [1150, "/media/business-card-mockup/mockupcarterose-1200.webp"],
      [1422, "/media/business-card-mockup/mockupcarterose-1484.webp"],
    ],
    fallback: "/media/business-card-mockup/mockupcarterose.png",
  },
  "business-card-mockup/palette-de-couleurs": {
    preset: "graphic",
    width: 1595,
    height: 1487,
    avif: [
      [640, "/media/business-card-mockup/palette-de-couleurs-640.avif"],
      [1200, "/media/business-card-mockup/palette-de-couleurs-1200.avif"],
      [1595, "/media/business-card-mockup/palette-de-couleurs-1595.avif"],
    ],
    fallback: "/media/business-card-mockup/palette-de-couleurs.png",
  },
  "clip/clip1": {
    preset: "photo",
    width: 2400,
    height: 1352,
    avif: [
      [640, "/media/clip/clip1-640.avif"],
      [1200, "/media/clip/clip1-1200.avif"],
      [2400, "/media/clip/clip1-2400.avif"],
    ],
    webp: [
      [640, "/media/clip/clip1-640.webp"],
      [1200, "/media/clip/clip1-1200.webp"],
      [2400, "/media/clip/clip1-2400.webp"],
    ],
    fallback: "/media/clip/clip1.jpg",
  },
  "clip/clip10": {
    preset: "photo",
    width: 1622,
    height: 912,
    avif: [
      [640, "/media/clip/clip10-640.avif"],
      [1200, "/media/clip/clip10-1200.avif"],
      [1622, "/media/clip/clip10-1622.avif"],
    ],
    webp: [
      [640, "/media/clip/clip10-640.webp"],
      [1200, "/media/clip/clip10-1200.webp"],
      [1622, "/media/clip/clip10-1622.webp"],
    ],
    fallback: "/media/clip/clip10.jpg",
  },
  "clip/clip11": {
    preset: "photo",
    width: 1990,
    height: 1118,
    avif: [
      [640, "/media/clip/clip11-640.avif"],
      [1200, "/media/clip/clip11-1200.avif"],
      [1990, "/media/clip/clip11-1990.avif"],
    ],
    webp: [
      [640, "/media/clip/clip11-640.webp"],
      [1200, "/media/clip/clip11-1200.webp"],
      [1990, "/media/clip/clip11-1990.webp"],
    ],
    fallback: "/media/clip/clip11.jpg",
  },
  "clip/clip12": {
    preset: "photo",
    width: 1992,
    height: 1114,
    avif: [
      [640, "/media/clip/clip12-640.avif"],
      [1200, "/media/clip/clip12-1200.avif"],
      [1992, "/media/clip/clip12-1992.avif"],
    ],
    webp: [
      [640, "/media/clip/clip12-640.webp"],
      [1200, "/media/clip/clip12-1200.webp"],
      [1992, "/media/clip/clip12-1992.webp"],
    ],
    fallback: "/media/clip/clip12.jpg",
  },
  "clip/clip2": {
    preset: "photo",
    width: 2400,
    height: 1377,
    avif: [
      [640, "/media/clip/clip2-640.avif"],
      [1200, "/media/clip/clip2-1200.avif"],
      [2400, "/media/clip/clip2-2400.avif"],
    ],
    webp: [
      [640, "/media/clip/clip2-640.webp"],
      [1200, "/media/clip/clip2-1200.webp"],
      [2400, "/media/clip/clip2-2400.webp"],
    ],
    fallback: "/media/clip/clip2.jpg",
  },
  "clip/clip3": {
    preset: "photo",
    width: 2400,
    height: 1377,
    avif: [
      [640, "/media/clip/clip3-640.avif"],
      [1200, "/media/clip/clip3-1200.avif"],
      [2400, "/media/clip/clip3-2400.avif"],
    ],
    webp: [
      [640, "/media/clip/clip3-640.webp"],
      [1200, "/media/clip/clip3-1200.webp"],
      [2400, "/media/clip/clip3-2400.webp"],
    ],
    fallback: "/media/clip/clip3.jpg",
  },
  "clip/clip4": {
    preset: "photo",
    width: 2400,
    height: 1381,
    avif: [
      [640, "/media/clip/clip4-640.avif"],
      [1200, "/media/clip/clip4-1200.avif"],
      [2400, "/media/clip/clip4-2400.avif"],
    ],
    webp: [
      [640, "/media/clip/clip4-640.webp"],
      [1200, "/media/clip/clip4-1200.webp"],
      [2400, "/media/clip/clip4-2400.webp"],
    ],
    fallback: "/media/clip/clip4.jpg",
  },
  "clip/clip5": {
    preset: "photo",
    width: 2400,
    height: 1372,
    avif: [
      [640, "/media/clip/clip5-640.avif"],
      [1200, "/media/clip/clip5-1200.avif"],
      [2400, "/media/clip/clip5-2400.avif"],
    ],
    webp: [
      [640, "/media/clip/clip5-640.webp"],
      [1200, "/media/clip/clip5-1200.webp"],
      [2400, "/media/clip/clip5-2400.webp"],
    ],
    fallback: "/media/clip/clip5.jpg",
  },
  "clip/clip6": {
    preset: "photo",
    width: 1622,
    height: 914,
    avif: [
      [640, "/media/clip/clip6-640.avif"],
      [1200, "/media/clip/clip6-1200.avif"],
      [1622, "/media/clip/clip6-1622.avif"],
    ],
    webp: [
      [640, "/media/clip/clip6-640.webp"],
      [1200, "/media/clip/clip6-1200.webp"],
      [1622, "/media/clip/clip6-1622.webp"],
    ],
    fallback: "/media/clip/clip6.jpg",
  },
  "clip/clip7": {
    preset: "photo",
    width: 1624,
    height: 916,
    avif: [
      [640, "/media/clip/clip7-640.avif"],
      [1200, "/media/clip/clip7-1200.avif"],
      [1624, "/media/clip/clip7-1624.avif"],
    ],
    webp: [
      [640, "/media/clip/clip7-640.webp"],
      [1200, "/media/clip/clip7-1200.webp"],
      [1624, "/media/clip/clip7-1624.webp"],
    ],
    fallback: "/media/clip/clip7.jpg",
  },
  "clip/clip8": {
    preset: "photo",
    width: 1614,
    height: 906,
    avif: [
      [640, "/media/clip/clip8-640.avif"],
      [1200, "/media/clip/clip8-1200.avif"],
      [1614, "/media/clip/clip8-1614.avif"],
    ],
    webp: [
      [640, "/media/clip/clip8-640.webp"],
      [1200, "/media/clip/clip8-1200.webp"],
      [1614, "/media/clip/clip8-1614.webp"],
    ],
    fallback: "/media/clip/clip8.jpg",
  },
  "clip/clip9": {
    preset: "photo",
    width: 1624,
    height: 912,
    avif: [
      [640, "/media/clip/clip9-640.avif"],
      [1200, "/media/clip/clip9-1200.avif"],
      [1624, "/media/clip/clip9-1624.avif"],
    ],
    webp: [
      [640, "/media/clip/clip9-640.webp"],
      [1200, "/media/clip/clip9-1200.webp"],
      [1624, "/media/clip/clip9-1624.webp"],
    ],
    fallback: "/media/clip/clip9.jpg",
  },
  "clip/image-youtube": {
    preset: "photo",
    width: 1280,
    height: 720,
    avif: [
      [640, "/media/clip/image-youtube-640.avif"],
      [1200, "/media/clip/image-youtube-1200.avif"],
      [1280, "/media/clip/image-youtube-1280.avif"],
    ],
    webp: [
      [640, "/media/clip/image-youtube-640.webp"],
      [1200, "/media/clip/image-youtube-1200.webp"],
      [1280, "/media/clip/image-youtube-1280.webp"],
    ],
    fallback: "/media/clip/image-youtube.jpg",
  },
  "cv/apercu": {
    preset: "graphic",
    width: 1697,
    height: 2400,
    avif: [
      [453, "/media/cv/apercu-640.avif"],
      [849, "/media/cv/apercu-1200.avif"],
      [1697, "/media/cv/apercu-2400.avif"],
    ],
    fallback: "/media/cv/apercu.png",
    alt: "Aperçu du CV de Lyna Rebahi (page 1)",
  },
  "festival-identite/crop-logo-negatif": {
    preset: "graphic",
    width: 1200,
    height: 1200,
    avif: [
      [640, "/media/festival-identite/crop-logo-negatif-640.avif"],
      [1200, "/media/festival-identite/crop-logo-negatif-1200.avif"],
    ],
    fallback: "/media/festival-identite/crop-logo-negatif.png",
  },
  "festival-identite/crop-logo-positif": {
    preset: "graphic",
    width: 1200,
    height: 1200,
    avif: [
      [640, "/media/festival-identite/crop-logo-positif-640.avif"],
      [1200, "/media/festival-identite/crop-logo-positif-1200.avif"],
    ],
    fallback: "/media/festival-identite/crop-logo-positif.png",
  },
  "festival-identite/crop-motifs": {
    preset: "graphic",
    width: 938,
    height: 938,
    avif: [
      [640, "/media/festival-identite/crop-motifs-640.avif"],
      [938, "/media/festival-identite/crop-motifs-938.avif"],
    ],
    fallback: "/media/festival-identite/crop-motifs.png",
  },
  "festival-identite/crop-picto": {
    preset: "graphic",
    width: 1200,
    height: 1200,
    avif: [
      [640, "/media/festival-identite/crop-picto-640.avif"],
      [1200, "/media/festival-identite/crop-picto-1200.avif"],
    ],
    fallback: "/media/festival-identite/crop-picto.png",
  },
  "festival-identite/crop-pole-ateliers": {
    preset: "graphic",
    width: 750,
    height: 750,
    avif: [
      [640, "/media/festival-identite/crop-pole-ateliers-640.avif"],
      [750, "/media/festival-identite/crop-pole-ateliers-750.avif"],
    ],
    fallback: "/media/festival-identite/crop-pole-ateliers.png",
  },
  "festival-identite/crop-pole-cuisine": {
    preset: "graphic",
    width: 750,
    height: 750,
    avif: [
      [640, "/media/festival-identite/crop-pole-cuisine-640.avif"],
      [750, "/media/festival-identite/crop-pole-cuisine-750.avif"],
    ],
    fallback: "/media/festival-identite/crop-pole-cuisine.png",
  },
  "festival-identite/crop-pole-education": {
    preset: "graphic",
    width: 750,
    height: 750,
    avif: [
      [640, "/media/festival-identite/crop-pole-education-640.avif"],
      [750, "/media/festival-identite/crop-pole-education-750.avif"],
    ],
    fallback: "/media/festival-identite/crop-pole-education.png",
  },
  "festival-identite/crop-pole-musique": {
    preset: "graphic",
    width: 750,
    height: 750,
    avif: [
      [640, "/media/festival-identite/crop-pole-musique-640.avif"],
      [750, "/media/festival-identite/crop-pole-musique-750.avif"],
    ],
    fallback: "/media/festival-identite/crop-pole-musique.png",
  },
  "festival-identite/crop-pole-soins": {
    preset: "graphic",
    width: 750,
    height: 750,
    avif: [
      [640, "/media/festival-identite/crop-pole-soins-640.avif"],
      [750, "/media/festival-identite/crop-pole-soins-750.avif"],
    ],
    fallback: "/media/festival-identite/crop-pole-soins.png",
  },
  "festival-identite/crop-texture": {
    preset: "graphic",
    width: 750,
    height: 750,
    avif: [
      [640, "/media/festival-identite/crop-texture-640.avif"],
      [750, "/media/festival-identite/crop-texture-750.avif"],
    ],
    fallback: "/media/festival-identite/crop-texture.png",
  },
  "festival-identite/planche-01": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-01-640.avif"],
      [1200, "/media/festival-identite/planche-01-1200.avif"],
      [2400, "/media/festival-identite/planche-01-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-01.png",
    alt: "Charte graphique Tafsut — logo",
  },
  "festival-identite/planche-09": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-09-640.avif"],
      [1200, "/media/festival-identite/planche-09-1200.avif"],
      [2400, "/media/festival-identite/planche-09-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-09.png",
    alt: "Charte graphique Tafsut — logo",
  },
  "festival-identite/planche-16": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-16-640.avif"],
      [1200, "/media/festival-identite/planche-16-1200.avif"],
      [2400, "/media/festival-identite/planche-16-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-16.png",
    alt: "Charte graphique Tafsut — palette de couleurs",
  },
  "festival-identite/planche-21": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-21-640.avif"],
      [1200, "/media/festival-identite/planche-21-1200.avif"],
      [2400, "/media/festival-identite/planche-21-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-21.png",
    alt: "Charte graphique Tafsut — typographies",
  },
  "festival-identite/planche-23": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-23-640.avif"],
      [1200, "/media/festival-identite/planche-23-1200.avif"],
      [2400, "/media/festival-identite/planche-23-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-23.png",
    alt: "Charte graphique Tafsut — affiche",
  },
  "festival-identite/planche-24": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-24-640.avif"],
      [1200, "/media/festival-identite/planche-24-1200.avif"],
      [2400, "/media/festival-identite/planche-24-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-24.png",
    alt: "Charte graphique Tafsut — affiche",
  },
  "festival-identite/planche-25": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-25-640.avif"],
      [1200, "/media/festival-identite/planche-25-1200.avif"],
      [2400, "/media/festival-identite/planche-25-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-25.png",
    alt: "Charte graphique Tafsut — billets",
  },
  "festival-identite/planche-27": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-27-640.avif"],
      [1200, "/media/festival-identite/planche-27-1200.avif"],
      [2400, "/media/festival-identite/planche-27-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-27.png",
    alt: "Charte graphique Tafsut — goodies",
  },
  "festival-identite/planche-28": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-28-640.avif"],
      [1200, "/media/festival-identite/planche-28-1200.avif"],
      [2400, "/media/festival-identite/planche-28-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-28.png",
    alt: "Charte graphique Tafsut — goodies",
  },
  "festival-identite/planche-31": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-31-640.avif"],
      [1200, "/media/festival-identite/planche-31-1200.avif"],
      [2400, "/media/festival-identite/planche-31-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-31.png",
    alt: "Charte graphique Tafsut — food truck",
  },
  "festival-identite/planche-32": {
    preset: "graphic",
    width: 2400,
    height: 1697,
    avif: [
      [640, "/media/festival-identite/planche-32-640.avif"],
      [1200, "/media/festival-identite/planche-32-1200.avif"],
      [2400, "/media/festival-identite/planche-32-2400.avif"],
    ],
    fallback: "/media/festival-identite/planche-32.png",
    alt: "Charte graphique Tafsut — signalétique",
  },
  "home/portrait": {
    preset: "photo",
    width: 1139,
    height: 1512,
    avif: [
      [482, "/media/home/portrait-640.avif"],
      [904, "/media/home/portrait-1200.avif"],
      [1139, "/media/home/portrait-1512.avif"],
    ],
    webp: [
      [482, "/media/home/portrait-640.webp"],
      [904, "/media/home/portrait-1200.webp"],
      [1139, "/media/home/portrait-1512.webp"],
    ],
    fallback: "/media/home/portrait.jpg",
  },
  "illustration-photoshop/affiche-sensibilisation-lyna-rebahi": {
    preset: "graphic",
    width: 1697,
    height: 2400,
    avif: [
      [452, "/media/illustration-photoshop/affiche-sensibilisation-lyna-rebahi-640.avif"],
      [848, "/media/illustration-photoshop/affiche-sensibilisation-lyna-rebahi-1200.avif"],
      [1697, "/media/illustration-photoshop/affiche-sensibilisation-lyna-rebahi-2400.avif"],
    ],
    fallback: "/media/illustration-photoshop/affiche-sensibilisation-lyna-rebahi.png",
  },
  "portraits-illustration/imad": {
    preset: "graphic",
    width: 1800,
    height: 2400,
    avif: [
      [480, "/media/portraits-illustration/imad-640.avif"],
      [900, "/media/portraits-illustration/imad-1200.avif"],
      [1800, "/media/portraits-illustration/imad-2400.avif"],
    ],
    fallback: "/media/portraits-illustration/imad.png",
  },
  "portraits-illustration/joseph": {
    preset: "graphic",
    width: 1758,
    height: 2400,
    avif: [
      [469, "/media/portraits-illustration/joseph-640.avif"],
      [879, "/media/portraits-illustration/joseph-1200.avif"],
      [1758, "/media/portraits-illustration/joseph-2400.avif"],
    ],
    fallback: "/media/portraits-illustration/joseph.png",
  },
  "portraits-illustration/lyna": {
    preset: "graphic",
    width: 1699,
    height: 2400,
    avif: [
      [453, "/media/portraits-illustration/lyna-640.avif"],
      [850, "/media/portraits-illustration/lyna-1200.avif"],
      [1699, "/media/portraits-illustration/lyna-2400.avif"],
    ],
    fallback: "/media/portraits-illustration/lyna.png",
  },
  "prototype-site-accessible/prototype1": {
    preset: "graphic",
    width: 814,
    height: 1472,
    avif: [
      [354, "/media/prototype-site-accessible/prototype1-640.avif"],
      [664, "/media/prototype-site-accessible/prototype1-1200.avif"],
      [814, "/media/prototype-site-accessible/prototype1-1472.avif"],
    ],
    fallback: "/media/prototype-site-accessible/prototype1.png",
  },
  "prototype-site-accessible/prototype2": {
    preset: "graphic",
    width: 818,
    height: 1440,
    avif: [
      [364, "/media/prototype-site-accessible/prototype2-640.avif"],
      [682, "/media/prototype-site-accessible/prototype2-1200.avif"],
      [818, "/media/prototype-site-accessible/prototype2-1440.avif"],
    ],
    fallback: "/media/prototype-site-accessible/prototype2.png",
  },
  "sae-1/flyer1": {
    preset: "graphic",
    width: 1414,
    height: 2000,
    avif: [
      [452, "/media/sae-1/flyer1-640.avif"],
      [848, "/media/sae-1/flyer1-1200.avif"],
      [1414, "/media/sae-1/flyer1-2000.avif"],
    ],
    fallback: "/media/sae-1/flyer1.png",
  },
  "sae-1/flyer2": {
    preset: "graphic",
    width: 1414,
    height: 2000,
    avif: [
      [452, "/media/sae-1/flyer2-640.avif"],
      [848, "/media/sae-1/flyer2-1200.avif"],
      [1414, "/media/sae-1/flyer2-2000.avif"],
    ],
    fallback: "/media/sae-1/flyer2.png",
  },
  "sae-1/logoprincipal": {
    preset: "graphic",
    width: 2400,
    height: 1351,
    avif: [
      [640, "/media/sae-1/logoprincipal-640.avif"],
      [1200, "/media/sae-1/logoprincipal-1200.avif"],
      [2400, "/media/sae-1/logoprincipal-2400.avif"],
    ],
    fallback: "/media/sae-1/logoprincipal.png",
  },
  "sae-1/logosecondaire": {
    preset: "graphic",
    width: 2400,
    height: 1354,
    avif: [
      [640, "/media/sae-1/logosecondaire-640.avif"],
      [1200, "/media/sae-1/logosecondaire-1200.avif"],
      [2400, "/media/sae-1/logosecondaire-2400.avif"],
    ],
    fallback: "/media/sae-1/logosecondaire.png",
  },
  "sae-1/maquette1": {
    preset: "graphic",
    width: 1248,
    height: 1602,
    avif: [
      [499, "/media/sae-1/maquette1-640.avif"],
      [935, "/media/sae-1/maquette1-1200.avif"],
      [1248, "/media/sae-1/maquette1-1602.avif"],
    ],
    fallback: "/media/sae-1/maquette1.png",
  },
  "sae-1/maquette3": {
    preset: "graphic",
    width: 1276,
    height: 1600,
    avif: [
      [510, "/media/sae-1/maquette3-640.avif"],
      [957, "/media/sae-1/maquette3-1200.avif"],
      [1276, "/media/sae-1/maquette3-1600.avif"],
    ],
    fallback: "/media/sae-1/maquette3.png",
  },
  "sae-1/maquette4": {
    preset: "graphic",
    width: 1234,
    height: 1592,
    avif: [
      [496, "/media/sae-1/maquette4-640.avif"],
      [930, "/media/sae-1/maquette4-1200.avif"],
      [1234, "/media/sae-1/maquette4-1592.avif"],
    ],
    fallback: "/media/sae-1/maquette4.png",
  },
  "sae-2/angerboda1": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/angerboda1-640.avif"],
      [960, "/media/sae-2/angerboda1-1200.avif"],
      [1080, "/media/sae-2/angerboda1-1350.avif"],
    ],
    fallback: "/media/sae-2/angerboda1.png",
  },
  "sae-2/angerboda2": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/angerboda2-640.avif"],
      [960, "/media/sae-2/angerboda2-1200.avif"],
      [1080, "/media/sae-2/angerboda2-1350.avif"],
    ],
    fallback: "/media/sae-2/angerboda2.png",
  },
  "sae-2/cerisicide1": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/cerisicide1-640.avif"],
      [960, "/media/sae-2/cerisicide1-1200.avif"],
      [1080, "/media/sae-2/cerisicide1-1350.avif"],
    ],
    fallback: "/media/sae-2/cerisicide1.png",
  },
  "sae-2/cerisicide2": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/cerisicide2-640.avif"],
      [960, "/media/sae-2/cerisicide2-1200.avif"],
      [1080, "/media/sae-2/cerisicide2-1350.avif"],
    ],
    fallback: "/media/sae-2/cerisicide2.png",
  },
  "sae-2/chartegraphique-skollrub": {
    preset: "graphic",
    width: 2400,
    height: 1335,
    avif: [
      [640, "/media/sae-2/chartegraphique-skollrub-640.avif"],
      [1200, "/media/sae-2/chartegraphique-skollrub-1200.avif"],
      [2400, "/media/sae-2/chartegraphique-skollrub-2400.avif"],
    ],
    fallback: "/media/sae-2/chartegraphique-skollrub.png",
  },
  "sae-2/etiquettes-skollrub-angerboda-1": {
    preset: "graphic",
    width: 1575,
    height: 788,
    avif: [
      [640, "/media/sae-2/etiquettes-skollrub-angerboda-1-640.avif"],
      [1200, "/media/sae-2/etiquettes-skollrub-angerboda-1-1200.avif"],
      [1575, "/media/sae-2/etiquettes-skollrub-angerboda-1-1575.avif"],
    ],
    fallback: "/media/sae-2/etiquettes-skollrub-angerboda-1.png",
  },
  "sae-2/etiquettes-skollrub-cerisicide-1": {
    preset: "graphic",
    width: 1575,
    height: 788,
    avif: [
      [640, "/media/sae-2/etiquettes-skollrub-cerisicide-1-640.avif"],
      [1200, "/media/sae-2/etiquettes-skollrub-cerisicide-1-1200.avif"],
      [1575, "/media/sae-2/etiquettes-skollrub-cerisicide-1-1575.avif"],
    ],
    fallback: "/media/sae-2/etiquettes-skollrub-cerisicide-1.png",
  },
  "sae-2/etiquettes-skollrub-freya-1": {
    preset: "graphic",
    width: 1575,
    height: 788,
    avif: [
      [640, "/media/sae-2/etiquettes-skollrub-freya-1-640.avif"],
      [1200, "/media/sae-2/etiquettes-skollrub-freya-1-1200.avif"],
      [1575, "/media/sae-2/etiquettes-skollrub-freya-1-1575.avif"],
    ],
    fallback: "/media/sae-2/etiquettes-skollrub-freya-1.png",
  },
  "sae-2/etiquettes-skollrub-original-1": {
    preset: "graphic",
    width: 1575,
    height: 788,
    avif: [
      [640, "/media/sae-2/etiquettes-skollrub-original-1-640.avif"],
      [1200, "/media/sae-2/etiquettes-skollrub-original-1-1200.avif"],
      [1575, "/media/sae-2/etiquettes-skollrub-original-1-1575.avif"],
    ],
    fallback: "/media/sae-2/etiquettes-skollrub-original-1.png",
  },
  "sae-2/freya1": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/freya1-640.avif"],
      [960, "/media/sae-2/freya1-1200.avif"],
      [1080, "/media/sae-2/freya1-1350.avif"],
    ],
    fallback: "/media/sae-2/freya1.png",
  },
  "sae-2/freya2": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/freya2-640.avif"],
      [960, "/media/sae-2/freya2-1200.avif"],
      [1080, "/media/sae-2/freya2-1350.avif"],
    ],
    fallback: "/media/sae-2/freya2.png",
  },
  "sae-2/moodboard-lyna": {
    preset: "photo",
    width: 1825,
    height: 1992,
    avif: [
      [586, "/media/sae-2/moodboard-lyna-640.avif"],
      [1099, "/media/sae-2/moodboard-lyna-1200.avif"],
      [1825, "/media/sae-2/moodboard-lyna-1992.avif"],
    ],
    webp: [
      [586, "/media/sae-2/moodboard-lyna-640.webp"],
      [1099, "/media/sae-2/moodboard-lyna-1200.webp"],
      [1825, "/media/sae-2/moodboard-lyna-1992.webp"],
    ],
    fallback: "/media/sae-2/moodboard-lyna.jpg",
  },
  "sae-2/original1": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/original1-640.avif"],
      [960, "/media/sae-2/original1-1200.avif"],
      [1080, "/media/sae-2/original1-1350.avif"],
    ],
    fallback: "/media/sae-2/original1.png",
  },
  "sae-2/original2": {
    preset: "graphic",
    width: 1080,
    height: 1350,
    avif: [
      [512, "/media/sae-2/original2-640.avif"],
      [960, "/media/sae-2/original2-1200.avif"],
      [1080, "/media/sae-2/original2-1350.avif"],
    ],
    fallback: "/media/sae-2/original2.png",
  },
  "sae-2/site1": {
    preset: "graphic",
    width: 2400,
    height: 1306,
    avif: [
      [640, "/media/sae-2/site1-640.avif"],
      [1200, "/media/sae-2/site1-1200.avif"],
      [2400, "/media/sae-2/site1-2400.avif"],
    ],
    fallback: "/media/sae-2/site1.png",
  },
  "sae-2/site2": {
    preset: "graphic",
    width: 2400,
    height: 1306,
    avif: [
      [640, "/media/sae-2/site2-640.avif"],
      [1200, "/media/sae-2/site2-1200.avif"],
      [2400, "/media/sae-2/site2-2400.avif"],
    ],
    fallback: "/media/sae-2/site2.png",
  },
  "sae-2/site3": {
    preset: "graphic",
    width: 2400,
    height: 1308,
    avif: [
      [640, "/media/sae-2/site3-640.avif"],
      [1200, "/media/sae-2/site3-1200.avif"],
      [2400, "/media/sae-2/site3-2400.avif"],
    ],
    fallback: "/media/sae-2/site3.png",
  },
  "sae-2/site4": {
    preset: "graphic",
    width: 2400,
    height: 1300,
    avif: [
      [640, "/media/sae-2/site4-640.avif"],
      [1200, "/media/sae-2/site4-1200.avif"],
      [2400, "/media/sae-2/site4-2400.avif"],
    ],
    fallback: "/media/sae-2/site4.png",
  },
  "sae-2/skollrub-logo-final": {
    preset: "graphic",
    width: 892,
    height: 775,
    avif: [
      [640, "/media/sae-2/skollrub-logo-final-640.avif"],
      [892, "/media/sae-2/skollrub-logo-final-892.avif"],
    ],
    fallback: "/media/sae-2/skollrub-logo-final.png",
  },
  "stop-motion/image-youtube": {
    preset: "photo",
    width: 1280,
    height: 720,
    avif: [
      [640, "/media/stop-motion/image-youtube-640.avif"],
      [1200, "/media/stop-motion/image-youtube-1200.avif"],
      [1280, "/media/stop-motion/image-youtube-1280.avif"],
    ],
    webp: [
      [640, "/media/stop-motion/image-youtube-640.webp"],
      [1200, "/media/stop-motion/image-youtube-1200.webp"],
      [1280, "/media/stop-motion/image-youtube-1280.webp"],
    ],
    fallback: "/media/stop-motion/image-youtube.jpg",
  },
} as const satisfies Record<string, ImageEntry>;

export type MediaId = keyof typeof images;

export const galleries = {
  "festival-identite": [
    "festival-identite/planche-01",
    "festival-identite/planche-09",
    "festival-identite/planche-16",
    "festival-identite/planche-21",
    "festival-identite/planche-24",
    "festival-identite/planche-23",
    "festival-identite/planche-25",
    "festival-identite/planche-27",
    "festival-identite/planche-28",
    "festival-identite/planche-32",
  ],
} as const satisfies Record<string, readonly MediaId[]>;

export const videos = {
  "cv": {
    src: "/media/video/cv-lyna-rebahi.mp4",
    width: 1920,
    height: 1080,
  },
  "hero": {
    src: "/media/video/hero.mp4",
    poster: "/media/video/hero-poster.webp",
    width: 1080,
    height: 574,
  },
} as const satisfies Record<string, VideoEntry>;
